### ISSUE TITLE
Asia/Calcutta is wrong; should be Asia/Kolkata

### ISSUE THREAD

**Issue by afgks** [KevinNovak/Time-Zone-Picker#2]
Calcutta is the old name of the city Kolkata and is not in use any more. The correct name of the time zone is Asia/Kolkata.

**Comment by afgks** [comment]
Asia/Rangoon is incorrect as well, should be Asia/Yangon

**Comment by KevinNovak** [comment]
The time zone map has been updated and now includes the updated names for `Asia/Kolkata` and `Asia/Yangon`:
https://zones.arilyn.cc/
